<?php
namespace MosPress\PluginStarter\Hook;
if ( ! defined( 'ABSPATH' ) ) exit;
use MosPress\PluginStarter\Helpers\Utils;
class Action_Hook
{
	/**
	 * The ID of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string    $plugin_name    The ID of this plugin.
	 */
	private $plugin_name;
    private static $instance = null;
    public static function get_instance()
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }
    public function __construct()
	{
        $this->plugin_name = 'plugin-starter';
        add_action('admin_init', [$this, 'plugin_starter_do_activation_redirect']);
        add_action('admin_menu', [$this, 'plugin_starter_admin_menu']);
		add_action('admin_enqueue_scripts', [$this, 'plugin_starter_dashboard_scripts']);
        add_action('current_screen', [$this, 'plugin_starter_hide_admin_notices']);
        add_action('admin_head', [$this, 'plugin_starter_option_form_submit']);
				
		add_action('admin_enqueue_scripts', [$this, 'plugin_starter_dashboard_scripts']);
		add_action('admin_enqueue_scripts', [$this, 'plugin_starter_dashboard_scripts']);
        add_action('upgrader_process_complete', [$this, 'plugin_starter_update_completed'], 10, 2);
		
    }

	/**
	 * Redirect to the welcome pages.
	 *
	 * @since    1.0.0
	 */
	public function plugin_starter_do_activation_redirect()
	{
		if (get_option('plugin_starter_do_activation_redirect')) {
			delete_option('plugin_starter_do_activation_redirect');
			wp_safe_redirect(admin_url('admin.php?page=' . $this->plugin_name));
		}
	}


	/**
	 * Adding menu to admin menu.
	 *
	 * @since    1.0.0
	 */
	public function plugin_starter_admin_menu()
	{
		add_menu_page(
			esc_html(PLUGIN_STARTER_NAME),
			esc_html(PLUGIN_STARTER_NAME),
			'manage_options',
			$this->plugin_name,
			array($this, 'plugin_starter_dashboard_html'),
			PLUGIN_STARTER_URL . 'assets/images/menu-icon.svg',
			57
		);
	}
	/**
	 * Loading plugin Welcome page.
	 *
	 * @since    1.0.0
	 */
	public function plugin_starter_dashboard_html()
	{
		if (!current_user_can('manage_options')) {
			return;
		}
		// include_once(PLUGIN_STARTER_PATH . 'admin/partials/' . $this->plugin_name . '-admin-display.php');
		echo '<div id="plugin-starter-settings-react-app" class="build-with-tailwind"></div>';
	}
	public function plugin_starter_dashboard_scripts($hook)
	{
		if ($hook !== 'toplevel_page_plugin-starter') {
			return;
		}

		// Automatically load dependencies and version generated by wp-scripts
		$asset_file = include(PLUGIN_STARTER_PATH . 'build/index.asset.php');

		wp_enqueue_script(
			'plugin-starter-react-app',
			PLUGIN_STARTER_URL . 'build/index.js',
			$asset_file['dependencies'],
			$asset_file['version'],
			true
		);

		// NEW: Enqueue Compiled Tailwind CSS
		wp_enqueue_style(
			'my-plugin-tailwind',
			PLUGIN_STARTER_URL . 'build/index.css',
			array(),
			$asset_file['version']
		);

	}
	public function plugin_starter_dashboard_react_page_html()
	{
		if (!current_user_can('manage_options')) {
			return;
		}
		include_once(PLUGIN_STARTER_PATH . 'admin/partials/' . $this->plugin_name . '-admin-display-react.php');
	}


	/**
	 * Removing all notieces from settings page.
	 *
	 * @since    1.0.0
	 */
	public function plugin_starter_hide_admin_notices()
	{
		// $current_screen = get_current_screen();
		// var_dump($current_screen->id);
		if (Utils::plugin_starter_is_plugin_page()) {
			remove_all_actions('user_admin_notices');
			remove_all_actions('admin_notices');
		}
	}
	public function plugin_starter_option_form_submit()
	{
		// $plugin_starter_options = array_replace_recursive(plugin_starter_get_option(), get_option('plugin_starter_options', []));
		if (isset($_POST['plugin_starter_options_form_field']) && wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['plugin_starter_options_form_field'])), 'plugin_starter_options_form_action')) {

			$err = 0;

			if (!$err) {
				$_POST['settings-updated'] = true;
			}

			// var_dump($_POST);
		}
		// update_option('plugin_starter_options', $plugin_starter_options);
	}
	public function plugin_starter_update_completed($upgrader_object, $options)
	{

		// If an update has taken place and the updated type is plugins and the plugins element exists
		if ($options['action'] == 'update' && $options['type'] == 'plugin' && isset($options['plugins'])) {
			foreach ($options['plugins'] as $plugin) {
				// Check to ensure it's my plugin
				if ($plugin == plugin_basename(PLUGIN_STARTER_MAIN_FILE)) {
					// do stuff here
					// $plugin_starter_options = array_replace_recursive(plugin_starter_get_option(), get_option('plugin_starter_options', []));
					// update_option('plugin_starter_options', $plugin_starter_options);
				}
			}
		}
	}
}